#!/bin/bash

mkdir -p /tmp/build
cd /tmp/build || exit 1
ls -la
cmake --target clean /tmp/server
rm -rf /tmp/build/*
cmake -LAH --parallel="${CORES}" -Wno-dev -GNinja -Wnostringop-truncation /tmp/server \
  -DCMAKE_USER_MAKE_RULES_OVERRIDE='/tmp/CMakeExtra.txt' \
  -DCMAKE_EXE_LINKER_FLAGS='-ltcmalloc' \
  -DWITH_NUMA=ON \
  -DWITH_PMEM=ON \
  -DWITH_SAFEMALLOC=OFF \
  -DCONC_WITH_UNITTEST=OFF \
  -DWITH_UNIT_TESTS=OFF \
  -DWITH_EMBEDDED_SERVER=OFF \
  -DWITH_UNIT_TESTS=OFF \
  -DWITH_WSREP=OFF \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DPLUGIN_ARCHIVE=NO \
  -DPLUGIN_AUTH_ED25519=NO \
  -DPLUGIN_AUTH_GSSAPI=NO \
  -DPLUGIN_AUTH_PAM=NO \
  -DPLUGIN_AUTH_PAM_V1=NO \
  -DPLUGIN_AUTH_TEST_PLUGIN=NO \
  -DPLUGIN_BLACKHOLE=NO \
  -DPLUGIN_CONNECT=YES \
  -DPLUGIN_CRACKLIB_PASSWORD_CHECK=NO \
  -DPLUGIN_DAEMON_EXAMPLE=NO \
  -DPLUGIN_DIALOG_EXAMPLES=NO \
  -DPLUGIN_EXAMPLE=NO \
  -DPLUGIN_EXAMPLE_KEY_MANAGEMENT=NO \
  -DPLUGIN_FEDERATED=YES \
  -DPLUGIN_FEDERATEDX=YES \
  -DPLUGIN_FEEDBACK=NO \
  -DPLUGIN_FTEXAMPLE=NO \
  -DPLUGIN_HANDLERSOCKET=YES \
  -DPLUGIN_MROONGA=NO \
  -DPLUGIN_OQGRAPH=NO \
  -DPLUGIN_SEQUENCE=NO \
  -DPLUGIN_SPIDER=NO \
  -DPLUGIN_SPHINX=NO \
  -DPLUGIN_TEST_SQL_DISCOVERY=NO \
  -DPLUGIN_TEST_SQL_SERVICE=NO \
  -DPLUGIN_TEST_VERSIONING=NO \
  -DTMPDIR=/tmp \
  -DCONNECT_WITH_MONGO=OFF \
  -DWITH_INNODB_LZ4=ON \
  -DWITH_ROCKSDB_JEMALLOC=ON \
  -DWITH_ROCKSDB_LZ4=ON \
  -DWITH_ROCKSDB_ZSTD=ON \
  -DWITH_ROCKSDB_snappy=OFF \
  -DPLUGIN_ROCKSDB=YES \
  -DMYSQL_MAINTAINER_MODE=NO \
  -DWITH_READLINE=ON \
  -DWITH_URING=ON \
  -DWITH_VALGRIND=ON 2>&1 | tee /tmp/up/ubuntu/cmake-options.txt

cmake --build /tmp/build/ --parallel "${CORES}" --target package | tee /tmp/up/ubuntu/cmake-output.txt
